"use client";

import { use, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { ISITHA_LOGO_DATA_URI } from "@/lib/brand";

type Feedback={id:string;round_number:number;outcome:string|null};
type Row={id:string;cv_decision:string;cv_comment:string|null;interview_status:string;interview_scheduled_at:string|null;interview_location:string|null;interview_meeting_link:string|null;interview_notes:string|null;candidate_applications:{candidate_name:string}|null;client_cvs:{candidate_name:string;recruiter_summary:string;professional_profile:string;skills:string;qualifications:string;experience:string;projects:string;additional_information:string}|null;client_interview_feedback:Feedback[]};
type Submission={id:string;status:string;message:string|null;expires_at:string|null;recruitment_clients:{company_name:string}|null;jobs:{title:string;location:string|null}|null;client_submission_candidates:Row[]};
const ratings=[1,2,3,4,5];

export default function ClientReview({params}:{params:Promise<{token:string}>}){
 const{token}=use(params);const supabase=useMemo(()=>createClient(),[]);const[data,setData]=useState<Submission|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
 useEffect(()=>{void load()},[token]);
 async function load(){const{data,error}=await supabase.rpc("get_client_review",{p_token:token});if(error||!data)setError("This review link is invalid, expired or no longer available.");else setData(data as Submission)}
 async function returnStaffOrReload(){const{data:{user}}=await supabase.auth.getUser();if(user){window.location.href="/";return}await load()}
 async function review(row:Row,decision:string,comment:string){setBusy(true);const{data,error}=await supabase.rpc("submit_client_cv_review",{p_token:token,p_candidate_id:row.id,p_decision:decision,p_comment:comment||null});setBusy(false);if(error||!data)return setError("We could not save that review. Please try again.");await returnStaffOrReload()}
 async function feedback(row:Row,form:HTMLFormElement){setBusy(true);const fd=new FormData(form);const value=(k:string)=>String(fd.get(k)||"").trim()||null;const rating=(k:string)=>value(k)?Number(value(k)):null;const{data,error}=await supabase.rpc("submit_client_interview_feedback",{p_token:token,p_candidate_id:row.id,p_interviewer:value("interviewer"),p_interview_date:value("interview_date"),p_technical_rating:rating("technical_rating"),p_experience_rating:rating("experience_rating"),p_communication_rating:rating("communication_rating"),p_team_fit_rating:rating("team_fit_rating"),p_overall_rating:rating("overall_rating"),p_strengths:value("strengths"),p_weaknesses:value("weaknesses"),p_salary_comments:value("salary_comments"),p_availability_comments:value("availability_comments"),p_general_comments:value("general_comments"),p_outcome:value("outcome")});setBusy(false);if(error||!data)return setError("We could not submit the interview feedback. Please try again.");form.reset();await returnStaffOrReload()}
 if(error)return <main className="min-h-screen bg-[#f4f6f8] p-8"><div className="mx-auto max-w-xl rounded-2xl bg-white p-8"><img src={ISITHA_LOGO_DATA_URI} className="w-48" alt="Isitha Global"/><p className="mt-8 font-semibold">{error}</p></div></main>;
 if(!data)return <main className="min-h-screen bg-[#f4f6f8] p-8">Loading client review…</main>;
 return <main className="min-h-screen bg-[#f4f6f8] text-[#172536]"><div className="mx-auto max-w-5xl px-5 py-7"><header className="border-b-2 border-[#c89a4b]/50 pb-5"><img src={ISITHA_LOGO_DATA_URI} className="w-52" alt="Isitha Global"/><p className="mt-5 text-xs font-extrabold uppercase tracking-widest text-[#a88436]">Private Client Review</p><h1 className="mt-2 text-3xl font-extrabold">{data.jobs?.title}</h1><p className="mt-2 text-[#667085]">Review candidates, arrange interviews with Isitha, and complete interview feedback when ready.</p></header><div className="mt-7 space-y-6">{data.client_submission_candidates.map(row=><CandidateCard key={row.id} row={row} busy={busy} review={review} feedback={feedback}/>)}</div><footer className="mt-10 border-t pt-5 text-sm text-[#667085]">Isitha Global · Global Professionals. Real Results</footer></div></main>
}

function CandidateCard({row,busy,review,feedback}:{row:Row;busy:boolean;review:(r:Row,d:string,c:string)=>Promise<void>;feedback:(r:Row,f:HTMLFormElement)=>Promise<void>}){
 const[decision,setDecision]=useState(row.cv_decision||"pending");const[comment,setComment]=useState(row.cv_comment||"");const cv=row.client_cvs;const scheduled=row.interview_status==='scheduled'||row.interview_status==='completed';
 return <section className="rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-bold uppercase text-[#a88436]">Candidate</p><h2 className="text-2xl font-extrabold">{row.candidate_applications?.candidate_name||cv?.candidate_name}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-bold uppercase">{row.cv_decision.replaceAll('_',' ')}</span></div>
 {cv&&<details className="mt-5 rounded-xl border p-4"><summary className="cursor-pointer font-bold">View client CV</summary>{[['Recruiter Summary',cv.recruiter_summary],['Professional Profile',cv.professional_profile],['Key Skills',cv.skills],['Qualifications',cv.qualifications],['Professional Experience',cv.experience],['Selected Projects',cv.projects],['Additional Information',cv.additional_information]].filter(([,v])=>v).map(([t,v])=><div key={t} className="mt-5"><h3 className="border-b border-[#c89a4b] pb-1 text-sm font-extrabold uppercase">{t}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{v}</p></div>)}</details>}
 {!scheduled&&<div className="mt-5 rounded-xl bg-slate-50 p-4"><h3 className="font-bold">Step 1 · CV decision</h3><div className="mt-3 grid gap-3 sm:grid-cols-[220px_1fr_auto]"><select value={decision} onChange={e=>setDecision(e.target.value)} className="rounded-lg border bg-white px-3 py-2"><option value="pending">Select decision</option><option value="interview">Invite to interview</option><option value="hold">Maybe / Hold</option><option value="do_not_interview">Do not interview</option></select><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Optional CV review comment" className="rounded-lg border px-3 py-2"/><button disabled={busy||decision==='pending'} onClick={()=>review(row,decision,comment)} className="rounded-lg bg-[#0b2239] px-4 py-2 font-bold text-white">Save</button></div></div>}
 {row.cv_decision==='interview'&&<div className="mt-5 rounded-xl border border-[#c89a4b]/40 p-5"><h3 className="text-lg font-bold">Interview arrangement</h3>{row.interview_status==='requested'&&<p className="mt-2 text-sm text-[#667085]">Interview requested. Isitha will contact you to arrange the date and time.</p>}{scheduled&&<div className="mt-3 rounded-lg bg-[#fff9ec] p-4 text-sm"><b>Interview scheduled</b>{row.interview_scheduled_at&&<p className="mt-1">{new Date(row.interview_scheduled_at).toLocaleString()}</p>}{row.interview_location&&<p>{row.interview_location}</p>}{row.interview_meeting_link&&<p><a className="font-bold underline" href={row.interview_meeting_link} target="_blank">Open meeting link</a></p>}{row.interview_notes&&<p className="mt-1">{row.interview_notes}</p>}</div>}
 {scheduled&&<details className="mt-4 rounded-xl border bg-white"><summary className="cursor-pointer list-none px-4 py-3 font-extrabold text-[#0b2239]">Interview Feedback <span className="float-right">▾</span></summary><div className="border-t p-4">{row.client_interview_feedback?.map(f=><div key={f.id} className="mb-3 rounded-lg bg-[#fff9ec] p-3 text-sm"><b>Round {f.round_number} submitted</b>{f.outcome&&<> · {f.outcome.replaceAll('_',' ')}</>}</div>)}<form className="grid gap-3 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();void feedback(row,e.currentTarget)}}><input name="interviewer" required placeholder="Interviewer name" className="rounded-lg border px-3 py-2"/><input name="interview_date" type="datetime-local" className="rounded-lg border px-3 py-2"/>{[['technical_rating','Technical / role knowledge'],['experience_rating','Relevant experience'],['communication_rating','Communication'],['team_fit_rating','Team / culture fit'],['overall_rating','Overall suitability']].map(([n,l])=><label key={n} className="text-sm font-semibold">{l}<select name={n} className="mt-1 w-full rounded-lg border px-3 py-2" required><option value="">Rate 1–5</option>{ratings.map(r=><option key={r}>{r}</option>)}</select></label>)}<textarea name="strengths" required placeholder="Strengths" className="rounded-lg border px-3 py-2 sm:col-span-2"/><textarea name="weaknesses" required placeholder="Weaknesses / concerns" className="rounded-lg border px-3 py-2 sm:col-span-2"/><textarea name="salary_comments" placeholder="Salary / package comments" className="rounded-lg border px-3 py-2"/><textarea name="availability_comments" placeholder="Availability / start date" className="rounded-lg border px-3 py-2"/><textarea name="general_comments" placeholder="General comments" className="rounded-lg border px-3 py-2 sm:col-span-2"/><select name="outcome" required className="rounded-lg border px-3 py-2 sm:col-span-2"><option value="">Interview outcome</option><option value="next_round">Proceed to next round</option><option value="hold">Hold</option><option value="reject">Do not proceed</option><option value="offer">Make offer</option></select><button disabled={busy} className="rounded-lg bg-[#c89a4b] px-5 py-3 font-extrabold text-[#0b2239] sm:col-span-2">Submit interview feedback</button></form></div></details>}</div>}
 </section>
}
