"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent,useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Job={id:string;title:string;client_company:string|null;status:string};

export default function ManualCandidateUpload(){
 const router=useRouter();const supabase=useMemo(()=>createClient(),[]);const[jobs,setJobs]=useState<Job[]>([]);const[saving,setSaving]=useState(false);const[message,setMessage]=useState("");const[authorised,setAuthorised]=useState(false);
 useEffect(()=>{void loadJobs()},[]);
 async function loadJobs(){const{data:{user},error:authError}=await supabase.auth.getUser();if(authError||!user){router.replace("/login");return}setAuthorised(true);const{data,error}=await supabase.from("jobs").select("id,title,client_company,status").order("created_at",{ascending:false});if(error){setMessage("Jobs could not be loaded. Please refresh or sign in again.");return}setJobs((data||[]) as Job[])}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!authorised||saving)return;const form=e.currentTarget;const fd=new FormData(form);const file=fd.get("cv");const jobId=String(fd.get("job_id")||"");if(!jobId){setMessage("Choose the job this CV relates to.");return}if(!(file instanceof File)||!file.size){setMessage("Attach the emailed CV.");return}const allowed=["application/pdf","application/msword","application/vnd.openxmlformats-officedocument.wordprocessingml.document"];if(!allowed.includes(file.type)||file.size>10*1024*1024){setMessage("CV must be PDF, DOC or DOCX and 10 MB or smaller.");return}setSaving(true);setMessage("");try{const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_");const path=`${jobId}/${crypto.randomUUID()}-${safe}`;const{error:uploadError}=await supabase.storage.from("candidate-cvs").upload(path,file,{upsert:false});if(uploadError)throw uploadError;const{error}=await supabase.from("candidate_applications").insert({job_id:jobId,candidate_name:String(fd.get("name")||"").trim(),email:String(fd.get("email")||"").trim().toLowerCase(),phone:String(fd.get("phone")||"").trim()||null,location:String(fd.get("location")||"").trim()||null,cv_path:path,status:"applied",popia_consent:false,popia_consent_at:null});if(error){await supabase.storage.from("candidate-cvs").remove([path]);throw error}form.reset();setMessage("Emailed CV added to the candidate pipeline. Source: received by email.");}catch(error){setMessage(error instanceof Error?error.message:"The CV could not be added.");}finally{setSaving(false)}}
 if(!authorised)return <main className="min-h-screen bg-[#f4f6f8] p-8 text-[#172536]">Checking recruiter access...</main>;
 const input="mt-2 w-full rounded-lg border border-[#cbd5df] bg-white px-4 py-3 text-[#172536] outline-none focus:border-[#c89a4b] focus:ring-4 focus:ring-[#c89a4b]/15";
 return <main className="min-h-screen bg-[#f4f6f8] text-[#172536]"><div className="mx-auto max-w-3xl px-5 py-8 sm:px-6"><div className="mb-6 flex items-center justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.12em] text-[#c89a4b]">Candidate intake</p><h1 className="mt-2 text-3xl font-extrabold text-[#0b2239]">Upload an emailed CV</h1><p className="mt-2 text-sm text-[#667085]">Add a CV received by email directly into the same recruitment pipeline.</p></div><Link href="/" className="rounded-lg border border-[#aebbc7] bg-white px-4 py-2 text-sm font-bold">Dashboard</Link></div><form onSubmit={submit} className="space-y-5 rounded-2xl border border-[#dfe5eb] bg-white p-7 shadow-sm"><label className="block text-sm font-bold">Job<select required name="job_id" className={input} defaultValue=""><option value="" disabled>Select job</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.title}{j.client_company?` — ${j.client_company}`:""}</option>)}</select></label><label className="block text-sm font-bold">Candidate name<input required name="name" className={input}/></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-bold">Email<input required type="email" name="email" className={input}/></label><label className="block text-sm font-bold">Phone<input name="phone" className={input}/></label></div><label className="block text-sm font-bold">Current location<input name="location" className={input}/></label><label className="block text-sm font-bold">CV received by email<input required name="cv" type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className={input}/><span className="mt-2 block text-xs font-normal text-[#667085]">PDF, DOC or DOCX — maximum 10 MB.</span></label><div className="rounded-xl border border-[#c89a4b]/35 bg-[#f3ead8]/55 p-4 text-xs leading-5 text-[#5b6470]">This route is for CVs already supplied to Isitha Global by the candidate or an authorised recruitment source. The record is added without falsely recording portal POPIA checkbox consent.</div>{message&&<p role="status" className="rounded-lg bg-[#f4f6f8] px-4 py-3 text-sm font-semibold">{message}</p>}<button disabled={saving} className="w-full rounded-lg bg-[#0b2239] px-5 py-3 font-bold text-white disabled:opacity-60">{saving?"Uploading...":"Add candidate & CV"}</button></form></div></main>;
}
