"use client";

import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase/client";

type QueueItem={id:string;candidate_name:string;cv_path:string;status:string;job_id:string;jobs:{title:string}|null};
type ClientCv={id?:string;application_id:string;candidate_name:string;recruiter_summary:string;professional_profile:string;skills:string;qualifications:string;experience:string;projects:string;additional_information:string;source_cv_path:string;status:string};

const empty=(a:QueueItem):ClientCv=>({application_id:a.id,candidate_name:a.candidate_name,recruiter_summary:"",professional_profile:"",skills:"",qualifications:"",experience:"",projects:"",additional_information:"",source_cv_path:a.cv_path,status:"draft"});

function escapeHtml(value:string){return value.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));}
function section(title:string,value:string){return value.trim()?`<h2>${title}</h2><div>${escapeHtml(value).replace(/\n/g,"<br>")}</div>`:"";}
function documentHtml(cv:ClientCv){return `<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(cv.candidate_name)} - Isitha CV</title><style>body{font-family:Arial,sans-serif;color:#111;max-width:820px;margin:40px auto;line-height:1.45}header{border-bottom:3px solid #111;padding-bottom:18px;margin-bottom:24px}h1{margin:0;font-size:30px}header p{margin:7px 0 0;color:#555}h2{font-size:15px;text-transform:uppercase;letter-spacing:.08em;margin:26px 0 9px;border-bottom:1px solid #ccc;padding-bottom:5px}.brand{font-weight:700;letter-spacing:.12em}</style></head><body><header><div class="brand">ISITHA RECRUITMENT</div><h1>${escapeHtml(cv.candidate_name)}</h1><p>Client CV</p></header>${section("Recruiter Summary",cv.recruiter_summary)}${section("Professional Profile",cv.professional_profile)}${section("Key Skills",cv.skills)}${section("Qualifications",cv.qualifications)}${section("Experience",cv.experience)}${section("Selected Projects",cv.projects)}${section("Additional Information",cv.additional_information)}</body></html>`;}

export default function ClientCvPage(){
 const supabase=useMemo(()=>createClient(),[]);const[queue,setQueue]=useState<QueueItem[]>([]);const[selected,setSelected]=useState<QueueItem|null>(null);const[cv,setCv]=useState<ClientCv|null>(null);const[working,setWorking]=useState(false);const[message,setMessage]=useState("");
 useEffect(()=>{void load()},[]);
 async function load(){const{data,error}=await supabase.from("candidate_applications").select("id,candidate_name,cv_path,status,job_id,jobs(title)").in("status",["client_cv","client_cv_ready"]).order("created_at",{ascending:true});if(error){setMessage("Client CV queue could not be loaded.");return}setQueue((data||[]) as unknown as QueueItem[])}
 async function selectItem(a:QueueItem){setSelected(a);setMessage("");const{data}=await supabase.from("client_cvs").select("*").eq("application_id",a.id).maybeSingle();setCv((data as ClientCv|null)||empty(a));}
 async function generate(){if(!selected||!cv)return;setWorking(true);setMessage("");try{const{data:{session}}=await supabase.auth.getSession();if(!session?.access_token){window.location.href="/login";return}const{data:signed,error}=await supabase.storage.from("candidate-cvs").createSignedUrl(selected.cv_path,300);if(error||!signed?.signedUrl)throw new Error("Original CV could not be opened.");const response=await fetch("/api/reformat-cv",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({cvUrl:signed.signedUrl,fileName:selected.cv_path.split("/").pop()||"candidate-cv",candidateName:selected.candidate_name,jobTitle:selected.jobs?.title||null})});const result=await response.json();if(!response.ok)throw new Error(result.error||"CV reformatting failed");const next={...cv,...result};setCv(next);const{data:saved,error:saveError}=await supabase.from("client_cvs").upsert({...next,generated_at:new Date().toISOString(),updated_at:new Date().toISOString()},{onConflict:"application_id"}).select().single();if(saveError)throw saveError;setCv(saved as ClientCv);await supabase.from("candidate_applications").update({status:"client_cv_ready"}).eq("id",selected.id);await load();setMessage("Client CV generated. Review it before exporting.");}catch(e){setMessage(e instanceof Error?e.message:"CV could not be generated.");}finally{setWorking(false)}}
 async function save(){if(!cv)return;const{data,error}=await supabase.from("client_cvs").upsert({...cv,updated_at:new Date().toISOString()},{onConflict:"application_id"}).select().single();if(error){setMessage("Changes could not be saved.");return}setCv(data as ClientCv);setMessage("Changes saved.")}
 function word(){if(!cv)return;const blob=new Blob([documentHtml(cv)],{type:"application/msword"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${cv.candidate_name.replace(/[^a-z0-9]+/gi,"-")}-Isitha-CV.doc`;a.click();URL.revokeObjectURL(url)}
 function pdf(){if(!cv)return;const w=window.open("","_blank");if(!w)return;w.document.write(documentHtml(cv));w.document.close();w.focus();setTimeout(()=>w.print(),250)}
 const fields:[keyof ClientCv,string][]=[["recruiter_summary","Recruiter summary"],["professional_profile","Professional profile"],["skills","Key skills"],["qualifications","Qualifications"],["experience","Experience"],["projects","Selected projects"],["additional_information","Additional information"]];
 return <main className="min-h-screen bg-slate-100"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-5"><div><h1 className="text-2xl font-bold">Client CV Builder</h1><p className="text-sm text-slate-500">Only candidates moved forward by your team appear here.</p></div><Link href="/" className="rounded border px-4 py-2 text-sm font-semibold">Dashboard</Link></div></header><div className="mx-auto grid max-w-7xl gap-6 px-6 py-8 lg:grid-cols-[340px_1fr]"><aside className="rounded-xl bg-white p-5 shadow-sm"><h2 className="font-bold">Ready for client CV</h2><p className="mt-1 text-sm text-slate-500">{queue.length} candidate{queue.length===1?"":"s"}</p><div className="mt-4 space-y-2">{queue.length===0?<p className="rounded border-2 border-dashed p-5 text-sm text-slate-500">No candidates have been moved forward yet.</p>:queue.map(a=><button key={a.id} onClick={()=>void selectItem(a)} className={`w-full rounded-lg border p-3 text-left ${selected?.id===a.id?"border-slate-900 bg-slate-50":"border-slate-200"}`}><div className="font-semibold">{a.candidate_name}</div><div className="text-xs text-slate-500">{a.jobs?.title||"Job"} · {a.status==="client_cv_ready"?"Draft ready":"Needs reformatting"}</div></button>)}</div></aside><section className="rounded-xl bg-white p-6 shadow-sm">{!cv?<div className="py-20 text-center text-slate-500">Select a candidate to prepare their client CV.</div>:<><div className="flex flex-wrap items-start justify-between gap-4 border-b pb-5"><div><p className="text-xs font-bold uppercase tracking-widest text-slate-400">Isitha Recruitment</p><h2 className="mt-1 text-3xl font-bold">{cv.candidate_name}</h2><p className="mt-1 text-sm text-slate-500">Personal contact details are removed from the client version.</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void generate()} disabled={working} className="rounded bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{working?"Reformatting...":cv.professional_profile?"Reformat again":"Reformat CV"}</button><button onClick={()=>void save()} className="rounded border px-4 py-2 text-sm font-semibold">Save</button><button onClick={word} className="rounded border px-4 py-2 text-sm font-semibold">Word</button><button onClick={pdf} className="rounded border px-4 py-2 text-sm font-semibold">PDF</button></div></div>{message&&<div className="mt-4 rounded bg-slate-50 p-3 text-sm">{message}</div>}<div className="mt-6 space-y-5">{fields.map(([key,label])=><div key={key}><label className="mb-2 block text-sm font-bold">{label}</label><textarea rows={key==="experience"?12:5} value={String(cv[key]||"")} onChange={e=>setCv({...cv,[key]:e.target.value})} className="w-full rounded-lg border border-slate-300 px-4 py-3"/></div>)}</div></>}</section></div></main>;
}
